CREATE TABLE Hoteles(
	ID INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	Telefono VARCHAR (150),
	Website VARCHAR (150),
	Email VARCHAR (150),
	PalabrasClave VARCHAR (250),
	Nombre VARCHAR (250),
	Descripcion VARCHAR (MAX),
	Direccion VARCHAR (250),
	Ciudad VARCHAR (250),
	CodigoPostal VARCHAR (5),
	Latitud NUMERIC (18,2),
	Longitud NUMERIC (18,2),
	Facturacion BIT,
	UsuarioID INT,
	Calificacion DECIMAL (18,2),
	Estatus BIT,
	Facebook VARCHAR (150),
	Whatsapp VARCHAR (150),
	Instagram VARCHAR (150),
)